import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { getSessionUser } from "@/lib/session";
import type { Prisma } from "@prisma/client";

export async function GET(req: Request) {
  const { searchParams } = new URL(req.url);
  const where: Prisma.NoticeWhereInput = { isApproved: true };
  const category = searchParams.get("category");
  if (category) where.category = category;
  const limit = Number(searchParams.get("limit") ?? "50");
  const notices = await db.notice.findMany({
    where,
    orderBy: [{ isPinned: "desc" }, { createdAt: "desc" }],
    take: limit,
  });
  return NextResponse.json(notices);
}

export async function POST(req: Request) {
  const user = await getSessionUser();
  if (!user || (user.role !== "admin" && user.role !== "teacher")) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  const body = await req.json();
  const created = await db.notice.create({
    data: {
      title: body.title,
      content: body.content,
      category: body.category || "general",
      affectedSemester: body.affectedSemester ?? null,
      affectedProgram: body.affectedProgram ?? null,
      postedById: user.id,
      postedByName: user.fullName,
      isPinned: !!body.isPinned,
      isApproved: true,
      isAutoGenerated: false,
      attachmentURL: body.attachmentURL ?? null,
      expiryDate: body.expiryDate ? new Date(body.expiryDate) : null,
    },
  });
  return NextResponse.json(created, { status: 201 });
}

export async function PUT(req: Request) {
  const user = await getSessionUser();
  if (!user || (user.role !== "admin" && user.role !== "teacher")) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  const body = await req.json();
  const { id, ...rest } = body;
  if (!id) return NextResponse.json({ error: "id required" }, { status: 400 });
  const notice = await db.notice.findUnique({ where: { id } });
  if (!notice) return NextResponse.json({ error: "Not found" }, { status: 404 });
  if (user.role === "teacher" && notice.postedById !== user.id) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }
  const updated = await db.notice.update({
    where: { id },
    data: {
      title: rest.title,
      content: rest.content,
      category: rest.category || notice.category,
      affectedSemester: rest.affectedSemester ?? null,
      affectedProgram: rest.affectedProgram ?? null,
      isPinned: !!rest.isPinned,
      attachmentURL: rest.attachmentURL ?? null,
      expiryDate: rest.expiryDate ? new Date(rest.expiryDate) : null,
    },
  });
  return NextResponse.json(updated);
}

export async function DELETE(req: Request) {
  const user = await getSessionUser();
  if (!user || (user.role !== "admin" && user.role !== "teacher")) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  const { searchParams } = new URL(req.url);
  const id = searchParams.get("id");
  if (!id) return NextResponse.json({ error: "id required" }, { status: 400 });
  const notice = await db.notice.findUnique({ where: { id } });
  if (!notice) return NextResponse.json({ error: "Not found" }, { status: 404 });
  // Teachers can only delete their own notices; admin can delete any
  if (user.role === "teacher" && notice.postedById !== user.id) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }
  await db.notice.delete({ where: { id } });
  return NextResponse.json({ ok: true });
}
