import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { getSessionUser } from "@/lib/session";
import type { Prisma } from "@prisma/client";

export async function GET(req: Request) {
  const { searchParams } = new URL(req.url);
  const where: Prisma.ScheduleChangeWhereInput = { isActive: true };
  const teacherId = searchParams.get("teacherId");
  const program = searchParams.get("program");
  const semester = searchParams.get("semester");
  if (teacherId) where.teacherId = teacherId;
  if (program) where.program = program;
  if (semester) where.semester = Number(semester);

  const changes = await db.scheduleChange.findMany({
    where,
    orderBy: { createdAt: "desc" },
    take: 100,
  });
  return NextResponse.json(changes);
}

export async function POST(req: Request) {
  const user = await getSessionUser();
  const isDev = process.env.NODE_ENV !== "production";

  // In dev mode, allow requests without a real session (for dev bypass).
  // Use a fallback dev user id; the teacherId comes from the request body.
  if (!isDev && (!user || (user.role !== "admin" && user.role !== "teacher"))) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const body = await req.json();

  // Resolve the "changedBy" user id. In dev mode without a session, try to
  // use the first admin user in the DB so the relation is valid.
  let changedById = user?.id;
  let changedByName = user?.fullName ?? "Developer";
  if (!changedById) {
    const adminUser = await db.user.findFirst({ where: { role: "admin" }, select: { id: true, fullName: true } });
    changedById = adminUser?.id;
    changedByName = adminUser?.fullName ?? "Developer";
  }

  const data: Prisma.ScheduleChangeCreateInput = {
    changeType: body.changeType,
    schedule: body.scheduleId ? { connect: { id: body.scheduleId } } : undefined,
    originalDay: body.originalDay ?? null,
    originalStartTime: body.originalStartTime ?? null,
    originalEndTime: body.originalEndTime ?? null,
    originalRoomId: body.originalRoomId ?? null,
    originalRoomNumber: body.originalRoomNumber ?? null,
    newDay: body.newDay ?? null,
    newStartTime: body.newStartTime ?? null,
    newEndTime: body.newEndTime ?? null,
    newRoomId: body.newRoomId ?? null,
    newRoomNumber: body.newRoomNumber ?? null,
    effectiveDate: body.effectiveDate ? new Date(body.effectiveDate) : new Date(),
    reason: body.reason ?? null,
    courseName: body.courseName ?? null,
    courseCode: body.courseCode ?? null,
    teacherId: body.teacherId ?? user?.id ?? null,
    teacherName: body.teacherName ?? user?.fullName ?? "Developer",
    semester: body.semester ?? null,
    program: body.program ?? null,
    changedBy: changedById ? { connect: { id: changedById } } : undefined,
    changedByName,
    isActive: true,
  };

  const change = await db.scheduleChange.create({ data });

  // Auto-generate a notice for the change
  const title =
    body.changeType === "cancelled"
      ? `Class Cancelled — ${body.courseCode ?? ""}`
      : body.changeType === "rescheduled"
      ? `Class Rescheduled — ${body.courseCode ?? ""}`
      : body.changeType === "room_changed"
      ? `Room Changed — ${body.courseCode ?? ""}`
      : `Extra Class — ${body.courseCode ?? ""}`;
  const content =
    body.changeType === "cancelled"
      ? `${body.courseName ?? ""} (${body.courseCode ?? ""}) scheduled on ${body.originalDay} at ${body.originalStartTime} has been cancelled.${body.reason ? ` Reason: ${body.reason}` : ""}`
      : body.changeType === "rescheduled"
      ? `${body.courseName ?? ""} (${body.courseCode ?? ""}) has been rescheduled from ${body.originalDay} ${body.originalStartTime} to ${body.newDay} ${body.newStartTime} at Room ${body.newRoomNumber}.`
      : body.changeType === "room_changed"
      ? `${body.courseName ?? ""} (${body.courseCode ?? ""}) room changed to ${body.newRoomNumber} for ${body.newDay} ${body.newStartTime}.`
      : `Extra ${body.courseName ?? ""} (${body.courseCode ?? ""}) class added on ${body.newDay} at ${body.newStartTime}, Room ${body.newRoomNumber}.`;

  await db.notice.create({
    data: {
      title,
      content,
      category: "schedule_change",
      changeType: body.changeType,
      scheduleChangeId: change.id,
      affectedSemester: body.semester ?? null,
      affectedProgram: body.program ?? null,
      postedById: changedById ?? null,
      postedByName: changedByName,
      isPinned: false,
      isApproved: true,
      isAutoGenerated: true,
    },
  });

  return NextResponse.json(change, { status: 201 });
}
