// Smart Routine Hub — Shared types

export type Role = "admin" | "teacher";

export type Program = "bsc" | "msc";

export type DayOfWeek =
  | "Saturday"
  | "Sunday"
  | "Monday"
  | "Tuesday"
  | "Wednesday"
  | "Thursday"
  | "Friday";

export const DAYS: DayOfWeek[] = [
  "Saturday",
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
];

export type ClassType = "theory" | "lab";

export type ChangeType = "cancelled" | "rescheduled" | "room_changed" | "extra_class";

export type NoticeCategory =
  | "academic"
  | "exam"
  | "event"
  | "general"
  | "schedule_change";

export interface User {
  id: string;
  email: string;
  fullName: string;
  designation?: string | null;
  department?: string | null;
  phone?: string | null;
  photoURL?: string | null;
  officeRoom?: string | null;
  bio?: string | null;
  role: Role;
  isActive: boolean;
}

export interface Course {
  id: string;
  name: string;
  code: string;
  creditHours: number;
  type: ClassType;
  semester: number;
  program: Program;
  isActive: boolean;
}

export interface Room {
  id: string;
  roomNumber: string;
  building?: string | null;
  type: "classroom" | "lab" | "seminar";
  capacity: number;
  isActive: boolean;
}

export interface TimeSlot {
  id: string;
  label: string;
  startTime: string;
  endTime: string;
  slotOrder: number;
  isBreak: boolean;
  isActive: boolean;
}

export interface Schedule {
  id: string;
  courseId: string;
  teacherId: string;
  roomId: string;
  timeSlotId?: string | null;
  courseName: string;
  courseCode: string;
  teacherName: string;
  teacherInitials?: string | null;
  roomNumber: string;
  startTime: string;
  endTime: string;
  dayOfWeek: DayOfWeek;
  semester: number;
  program: Program;
  section?: string | null;
  classType: ClassType;
  isActive: boolean;
}

export interface ScheduleChange {
  id: string;
  scheduleId?: string | null;
  changeType: ChangeType;
  originalDay?: string | null;
  originalStartTime?: string | null;
  originalEndTime?: string | null;
  originalRoomId?: string | null;
  originalRoomNumber?: string | null;
  newDay?: string | null;
  newStartTime?: string | null;
  newEndTime?: string | null;
  newRoomId?: string | null;
  newRoomNumber?: string | null;
  effectiveDate?: string | null;
  reason?: string | null;
  courseName?: string | null;
  courseCode?: string | null;
  teacherId?: string | null;
  teacherName?: string | null;
  semester?: number | null;
  program?: string | null;
  changedById?: string | null;
  changedByName?: string | null;
  isActive: boolean;
  createdAt: string;
}

export interface Notice {
  id: string;
  title: string;
  content: string;
  category: NoticeCategory;
  changeType?: string | null;
  scheduleChangeId?: string | null;
  affectedSemester?: number | null;
  affectedProgram?: string | null;
  postedById?: string | null;
  postedByName?: string | null;
  isPinned: boolean;
  isApproved: boolean;
  isAutoGenerated: boolean;
  attachmentURL?: string | null;
  expiryDate?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface LibraryLink {
  id: string;
  degree: "bsc" | "msc" | "others";
  semester?: number | null;
  url: string;
  title: string;
  isActive: boolean;
}

export interface SiteSettings {
  siteName: string;
  siteTagline: string;
  departmentName: string;
  universityName: string;
  contactEmail: string;
  contactPhone: string;
  address: string;
  aboutText: string;
  headerLinks: { label: string; href: string }[];
  footerDescription: string;
  footerQuickLinks: { label: string; href: string }[];
  socialMedia: { name: string; url: string; icon: string }[];
  developerName: string;
  developerUrl: string;
  academicSession: string;
}

export const DEFAULT_SETTINGS: SiteSettings = {
  siteName: "Smart Routine Hub",
  siteTagline: "ICE-RU Department Management System",
  departmentName: "Department of Information & Communication Engineering",
  universityName: "University of Rajshahi",
  contactEmail: "ice@ru.ac.bd",
  contactPhone: "+880 721-750-123",
  address: "3rd Science Building, University of Rajshahi, Rajshahi 6205, Bangladesh",
  aboutText:
    "The Department of Information & Communication Engineering at the University of Rajshahi is committed to excellence in teaching, research, and innovation in computing and communication technologies.",
  headerLinks: [
    { label: "Home", href: "/?view=home" },
    { label: "Master Routine", href: "/?view=master-calendar" },
    { label: "Student", href: "/?view=student" },
    { label: "Library", href: "/?view=library" },
  ],
  footerDescription:
    "Official academic schedule management portal for the ICE Department, University of Rajshahi. Real-time class routines, notices and resource library.",
  footerQuickLinks: [
    { label: "Home", href: "/?view=home" },
    { label: "Master Routine", href: "/?view=master-calendar" },
    { label: "Student View", href: "/?view=student" },
    { label: "Library", href: "/?view=library" },
    { label: "Login", href: "/login" },
  ],
  socialMedia: [
    { name: "Facebook", url: "https://facebook.com/iceru", icon: "facebook" },
    { name: "Website", url: "https://ru.ac.bd/ice", icon: "globe" },
    { name: "Email", url: "mailto:ice@ru.ac.bd", icon: "mail" },
  ],
  developerName: "ICE Tech Team",
  developerUrl: "https://ru.ac.bd",
  academicSession: "Spring 2026",
};

// Map teacher initials -> full name (used across the app)
export const TEACHER_PROFILES: Record<string, { name: string; designation: string }> = {
  MRH: { name: "Dr. Md. Rafiqul Hasan", designation: "Professor" },
  NHF: { name: "Dr. Nurul Haque Faruque", designation: "Professor" },
  MAA: { name: "Dr. Md. Anisur Rahman", designation: "Professor" },
  MSI: { name: "Dr. Md. Shafiul Islam", designation: "Professor" },
  IAZ: { name: "Dr. Ishtiaq Ahmed Zaman", designation: "Associate Professor" },
  TR: { name: "Dr. Tariqur Rahman", designation: "Professor" },
  MMH: { name: "Dr. Md. Mahfuzur Rahman", designation: "Professor" },
  MAH: { name: "Dr. Md. Anwar Hossain", designation: "Professor" },
  EA: { name: "Dr. Esrat Ara", designation: "Professor" },
  NF: { name: "Dr. Nazmul Hasan Farid", designation: "Associate Professor" },
  AR: { name: "Dr. Ataur Rahman", designation: "Associate Professor" },
  PKS: { name: "Dr. Pranab Kumar Saha", designation: "Associate Professor" },
  MRI: { name: "Dr. Md. Rafiqul Islam", designation: "Associate Professor" },
  TAS: { name: "Dr. Tanvir Ahmed Sarker", designation: "Assistant Professor" },
  JF: { name: "Dr. Jakia Ferdous", designation: "Assistant Professor" },
  NS: { name: "Dr. Nuruzzaman Sarker", designation: "Assistant Professor" },
  MMB: { name: "Dr. Md. Muktadir Billah", designation: "Assistant Professor" },
  RH: { name: "Dr. Rezwanul Hasan", designation: "Assistant Professor" },
  MO: { name: "Dr. Mahbub Ovi", designation: "Lecturer" },
  MMI: { name: "Dr. Md. Moinul Islam", designation: "Lecturer" },
  FH: { name: "Dr. Farhana Haque", designation: "Assistant Professor" },
  AFS: { name: "Dr. AFM Saleh", designation: "Professor" },
  MHR: { name: "Dr. Md. Harunur Rashid", designation: "Professor" },
  NA: { name: "Dr. Nusrat Ara", designation: "Professor" },
  SNS: { name: "Dr. SM Najmus Sakib", designation: "Associate Professor" },
  AUM: { name: "Dr. Ashraf Uddin Mahmud", designation: "Associate Professor" },
  AAZ: { name: "Dr. ASM Amanullah Zaman", designation: "Associate Professor" },
  TFS: { name: "Dr. Tasnim Fatema Sultana", designation: "Assistant Professor" },
  SS: { name: "Dr. Sumaiya Sultana", designation: "Assistant Professor" },
  HI: { name: "Dr. Humaira Islam", designation: "Assistant Professor" },
};

// Course code -> human friendly name
export const COURSE_NAMES: Record<string, string> = {
  CSE113: "Structured Programming",
  CSE114: "Structured Programming Lab",
  CSE117: "Introduction to ICT",
  CSE112: "Discrete Mathematics",
  CSE121: "Data Structures",
  CSE122: "Data Structures Lab",
  CSE123: "Object Oriented Programming",
  CSE124: "OOP Lab",
  EEE117: "Electrical Circuits",
  EEE127: "Electronic Devices & Circuits",
  EEE128: "Electronic Devices & Circuits Lab",
  MAT115: "Differential & Integral Calculus",
  MAT125: "Coordinate Geometry & Linear Algebra",
  PHY111: "Physics I",
  PHY121: "Physics II",
  PHY122: "Physics Lab",
  ENG111: "English Language I",
  ENG127: "English Language II",
  CSE213: "Algorithms",
  CSE214: "Algorithms Lab",
  CSE215: "Digital Logic Design",
  CSE216: "Digital Logic Design Lab",
  CSE221: "Database Systems",
  CSE222: "Database Systems Lab",
  CSE223: "Computer Architecture",
  CSE224: "Computer Architecture Lab",
  CSE225: "Operating Systems",
  CSE226: "Operating Systems Lab",
  CSE227: "Software Engineering",
  CSE229: "Numerical Methods",
  MAT213: "Complex Analysis & Laplace",
  MAT217: "Statistics & Probability",
  MAT317: "Discrete Math II",
  MAT323: "Optimization Techniques",
  ENS221: "Environmental Science",
  ACT215: "Accounting Fundamentals",
  BAN211: "Bangla & Bangladesh Studies",
  CSE311: "Data Communication",
  CSE313: "Computer Networks",
  CSE314: "Computer Networks Lab",
  CSE315: "Web Engineering",
  CSE316: "Web Engineering Lab",
  CSE317: "Theory of Computation",
  CSE318: "Theory of Computation Lab",
  CSE321: "Artificial Intelligence",
  CSE322: "AI Lab",
  CSE323: "Machine Learning",
  CSE324: "Machine Learning Lab",
  CSE325: "Computer Graphics",
  CSE326: "Computer Graphics Lab",
  MGT329: "Engineering Management",
  CSE411: "Cyber Security",
  CSE412: "Cyber Security Lab",
  CSE413: "Cloud Computing",
  CSE414: "Cloud Computing Lab",
  CSE415: "Mobile Application Development",
  CSE416: "Mobile App Development Lab",
  CSE417: "Software Project Management",
  CSE418: "Software Project Management Lab",
  CSE419: "Big Data Analytics",
  CSE421: "Bioinformatics",
  CSE423: "Distributed Systems",
  CSE469: "Thesis / Capstone Project",
  MGT417: "IT Entrepreneurship",
};

export const SEMESTER_LABELS = ["1st", "2nd", "3rd", "4th", "5th", "6th", "7th", "8th"];

export function semesterLabel(n: number): string {
  return SEMESTER_LABELS[n - 1] ?? `${n}th`;
}
